INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Vegan');
INSERT INTO category (description) VALUES ('Avocado');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (uom) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (uom) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (uom) VALUES ('Cup');
INSERT INTO unit_of_measure (uom) VALUES ('Pinch');
INSERT INTO unit_of_measure (uom) VALUES ('Ounce');
INSERT INTO unit_of_measure (uom) VALUES ('Bash');
INSERT INTO unit_of_measure (uom) VALUES ('Serrano');
INSERT INTO unit_of_measure (uom) VALUES ('Ripe');
