INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_mesure (uom) VALUES ('Teaspoon');
INSERT INTO unit_of_mesure (uom) VALUES ('Tablespoon');
INSERT INTO unit_of_mesure (uom) VALUES ('Cup');
INSERT INTO unit_of_mesure (uom) VALUES ('Pinch');
INSERT INTO unit_of_mesure (uom) VALUES ('Ounce');
INSERT INTO unit_of_mesure (uom) VALUES ('Tbsp');
INSERT INTO unit_of_mesure (uom) VALUES ('Bash');
INSERT INTO unit_of_mesure (uom) VALUES ('Serrano');
INSERT INTO unit_of_mesure (uom) VALUES ('ripe');
